export const ARTICLES_ALL_REQUEST = "ARTICLES_ALL_REQUEST"
export const ARTICLES_ALL_FAILURE = "ARTICLES_ALL_FAILURE"
export const ARTICLES_ALL_RESPONSE = "ARTICLES_ALL_RESPONSE"

export const ARTICLES_ADD_MANY_REQUEST = "ARTICLES_ADD_MANY_REQUEST"
export const ARTICLES_ADD_MANY_RESPONSE = "ARTICLES_ADD_MANY_RESPONSE"
